name: "\U0001F30F Environment"
description: "ì¶”ê°€ì ì¸ í™˜ê²½ì„¤ì •ì´ í•„ìš”í•œê°€ìš”?"
labels: "\U0001F30F Environment"
body:
  - type: textarea
    attributes:
      label: ğŸ¤” ì¶”ê°€í•´ì•¼ í•˜ëŠ” ì´ìœ 
      description: í™˜ê²½ì„¤ì •ì„ ì¶”ê°€í•´ì•¼ í•˜ëŠ” ì´ìœ ë¥¼ ì„¤ëª…í•´ ì£¼ì„¸ìš”.
    validations:
      required: true
  - type: textarea
    attributes:
      label: âœ… ì‘ì—…
      description: ì¶”ê°€í•  í™˜ê²½ì„¤ì •ì— ëŒ€í•´ ê°„ëµíˆ ê¸°ë¡í•´ ì£¼ì„¸ìš”.
    validations:
      required: true
  - type: textarea
    attributes:
      label: ğŸ™‹ğŸ» More
      description: ë” í•˜ê³  ì‹¶ì€ ë§ì´ ìˆë‹¤ë©´ ì‘ì„±í•´ ì£¼ì„¸ìš”.
